### ISSUE TITLE
Addon isn't working

### ISSUE THREAD

**Issue by StanDude** [Phanx/OPieMasque#1]
Hey, to be precise, the addon simply doesn't show. It does nothing, it doesn't show up, it's like its not there. Any solution to this? 

I checked if it was enabled and it was.

**Comment by Phanx** [comment]
Doesn't show where?

-------- Original Message --------

**Comment by Phanx** [comment]
Works fine for me with OPie Vanilla 1, Masque 7.3.0, and OPie Masque 7.1.0.0 in WoW 7.3.5. Make sure you have all three addons up to date and enabled -- OPie Masque is just a "bridge" that applies Masque skinning features to OPie; it doesn't do anything on its own. If you're still having problems, report back with the versions of all 3 addons you have installed, and be more specific about where you're looking (on OPie? in the Masque options? what do your Masque settings for OPie look like?).
